set(TESTSVCPLUGIN_NAME testSvcPlugin)

file(GLOB TESTSVCPLUGIN_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTSVCPLUGIN_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TESTSVCPLUGIN_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TESTSVCPLUGIN_INC_TD  ${NATID_SDK_INC}/td/*.h)
file(GLOB TESTSVCPLUGIN_INC_GUI ${NATID_SDK_INC}/gui/*.h)
file(GLOB TESTSVCPLUGIN_INC_SYST ${NATID_SDK_INC}/syst/*.h)
file(GLOB TESTSVCPLUGIN_INC_SC ${NATID_SDK_INC}/sc/*.h)
file(GLOB TESTSVCPLUGIN_INC_FO ${NATID_SDK_INC}/fo/*.h)
file(GLOB TESTSVCPLUGIN_INC_ARCH ${NATID_SDK_INC}/arch/*.h)

# add executable
add_executable(${TESTSVCPLUGIN_NAME} ${TESTSVCPLUGIN_INCS} ${TESTSVCPLUGIN_SOURCES} ${TESTSVCPLUGIN_INC_TD}
			${TESTSVCPLUGIN_INC_GUI} ${TESTSVCPLUGIN_INC_SYST} ${TESTSVCPLUGIN_INC_SC} ${TESTSVCPLUGIN_INC_FO} ${TESTSVCPLUGIN_INC_ARCH} )

source_group("inc"            FILES ${TESTSVCPLUGIN_INCS})
source_group("inc\\td"        FILES ${TESTSVCPLUGIN_INC_TD})
source_group("inc\\gui"        FILES ${TESTSVCPLUGIN_INC_GUI})
source_group("inc\\arch"        FILES ${TESTSVCPLUGIN_INC_ARCH})
source_group("inc\\fo"        FILES ${TESTSVCPLUGIN_INC_FO})
source_group("inc\\sc"        FILES ${TESTSVCPLUGIN_INC_SC})
source_group("inc\\syst"        FILES ${TESTSVCPLUGIN_INC_SYST})

source_group("src"            FILES ${TESTSVCPLUGIN_SOURCES})

target_link_libraries(${TESTSVCPLUGIN_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG}
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

set(PLUGIN_DIR_LOG "$<$<CONFIG:Release>:${CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE}>$<$<CONFIG:Debug>:${CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG}>")

# Pass it as a macro definition to the application code
target_compile_definitions(${TESTSVCPLUGIN_NAME} PRIVATE
    PLUGIN_DIR="${PLUGIN_DIR_LOG}"
)

setTargetPropertiesForGUIApp(${TESTSVCPLUGIN_NAME} ${TESTSVCPLUGIN_PLIST})

setIDEPropertiesForGUIExecutable(${TESTSVCPLUGIN_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTSVCPLUGIN_NAME})
